import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import { Providers } from './providers'
import StyledComponentsRegistry from '@/lib/register'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} ${roboto.className}`}>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
